name: Demo Expression
run-name: ${{github.actor}} Demo Expression
on:
  push:
    branches:
      - "expression"

jobs:
  Demo-Expression:
    runs-on: ubuntu-latest
    steps:
      - name: Github expression
        run: echo "${{github.actor}} ${{github.event_name}} ${{github.repository}} ${{github.workspace}} ${{github.ref}} ${{github.job}}"

  